"""quantity column

Revision ID: 7c147fb18348
Revises: 180fcf42ee00
Create Date: 2023-11-30 14:28:12.470188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c147fb18348'
down_revision = '180fcf42ee00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))
        op.execute('UPDATE item SET quantity = 1 WHERE quantity IS NULL')
        op.alter_column('item', 'quantity', nullable=False)
        

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
